export const HEADER_HEIGHT = 60
export const FOOTER_CAP_HEIGHT = 70
export const DEFAULT_FOOTER_CAP_HEIGHT = 65 + HEADER_HEIGHT
export const FOOTER_WITH_RESOURCE_CAP_HEIGHT = 121 + HEADER_HEIGHT
export const FOOTER_WITH_AUDIO_CAP_HEIGHT = 81 + HEADER_HEIGHT
export const FOOTER_WITH_IMAGE_CAP_HEIGHT = 123 + HEADER_HEIGHT